<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.2.0.2</Version>
    <Authors>Roxyz0501</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepoUrl>https://github.com/Roxyz0501/RetainerRecall</RepoUrl>
    <IconUrl>https://raw.githubusercontent.com/Roxyz0501/RetainerRecall/main/images/icon.png</IconUrl>
    <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup><Compile Remove="Tests/**/*.cs" /></ItemGroup>
</Project>
