<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DalamudLibPath>$(appdata)/XIVLauncher/addon/Hooks/dev/</DalamudLibPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../NativeButton.cs" Link="NativeButton.cs" />
    <Reference Include="FFXIVClientStructs" HintPath="$(DalamudLibPath)FFXIVClientStructs.dll" />
    <Reference Include="InteropGenerator.Runtime" HintPath="$(DalamudLibPath)InteropGenerator.Runtime.dll" />
  </ItemGroup>
</Project>
